### ISSUE TITLE
Error messages when building mixed project (>80% C++) not verbose enough for troubleshooting

### ISSUE THREAD

**Issue by jonhall54** [AppThreat/atom#151]
atom runs for a while (>20 mins) and creates app.atom file, and sometime usages.json. However the process comes back as "killed" with no further information.
Command used based on [cdxgen documentation](https://cyclonedx.github.io/cdxgen/#/ADVANCED?id=use-atom-in-java-mode) for a large project.
`./atom -J-Xmx16g usages -o app.atom -v --slice-outfile usages.json -l c++ <PATH TO CLONED REPO>`

Any way I can get further information out of atom?

**Comment by prabhu** [comment]
@jonhall54 How big is the project? Currently we run all the frontends with the logging disabled, so running a profiler is the only option as of now.

**Comment by jonhall54** [comment]
Including dependencies in full it's approx 4GB - running over SSH so not sure if a graphical frontend is missing and throwing an error?

**Comment by prabhu** [comment]
Can you try creating just the atom with -l h? Remove the word usages from your commands.

**Comment by jonhall54** [comment]
@prabhu I am attempting this, and thanks for the advice - how long would you expect atom to complete? Running overnight last night it didn't get killed, but seems to hang after an error `Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "scala-execution-context-global-20"` I will increase the memory in the command and see what happens

**Comment by prabhu** [comment]
Time taken is based on memory available. Best to try with smaller projects to get a feel before trying with larger projects

**Comment by jonhall54** [comment]
@prabhu I've had some improved results making use of cmake `CMAKE_EXPORT_COMPILE_COMMANDS` based on: https://github.com/CycloneDX/cdxgen/issues/1115. I now get an `app.atom` and `slices.json` files which are not corrupted and work having run cmake.

However, the output does not include many of the 3rd party dependencies I know are present, and running cdxgen does not provide additional insight. Seems my best working method right now is to extract the dependencies into a conanfile.txt (not using conan for build) and then run cdxgen to get dependency info.

**Comment by prabhu** [comment]
Could you share an example code snippet for a dependency that was not captured in the slices?
