### ISSUE TITLE
Failure: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1

### ISSUE THREAD

**Issue by almaz045** [AppThreat/atom#153]
Hi! I noticed error when I run atom on repos like [react](https://github.com/facebook/react) and [three.js](https://github.com/mrdoob/three.js):
atom -o app.atom -l js .

Failure: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1

**Comment by prabhu** [comment]
I can replicate this with the three.js repo locally. Investigating ...

**Comment by prabhu** [comment]
Removing the JavaScript Type Recovery results in a successful atom creation.

```
new JavaScriptTypeRecoveryPass(ag).createAndApply()
```
